### ISSUE TITLE
直接运行访问某些网址无法代理

### ISSUE THREAD

**Issue by mywaiting** [binux/pyproxy#1]
直接运行访问某些网址无法代理

例如直接访问：  `localhost:8888/?method=get&url=http://www.qq.com`

另外，这个proxy能整个过滤，过滤返回的页面内容，如 css、js、img等通过proxy来访问就更好了

实在懒得自己写代码了，拿来主义，请见谅

**Comment by binux** [comment]
https://gist.github.com/binux/3663115

**Comment by binux** [comment]
localhost:8888/?method=get&url=http://www.qq.com
并没有任何问题啊
